/**
 * DNA Android Tools.
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2015 Die Netzarchitekten e.U., Benjamin Erhart
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.netzarchitekten.tools;

import android.annotation.SuppressLint;
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.os.Build;

/**
 * <p>
 * Encapsulates deprecation warning for
 * {@link android.content.res.Resources#getColor(int)} since Android Marshmallow
 * (API 23) and {@link android.content.res.Resources#getDrawable(int)} since
 * Android Lollipop MR1 (API 22).
 * </p>
 * <p>
 * Contains a static and an OO interface.
 * </p>
 *
 * @author Benjamin Erhart {@literal <berhart@netzarchitekten.com>}
 */
public class Resources {

    private final android.content.res.Resources mResources;

    /**
     * @param context
     *            A context object to access the
     *            {@link android.content.res.Resources} of the app.
     */
    public Resources(Context context) {
        mResources = context.getResources();
    }

    /**
     * Honor deprecation of {@link android.content.res.Resources#getColor(int)}
     * since API 23.
     *
     * @param id
     *            The desired resource identifier, as generated by the aapt
     *            tool. This integer encodes the package, type, and resource
     *            entry. The value 0 is an invalid identifier.
     * @return a single color value in the form 0xAARRGGBB.
     * @see android.content.res.Resources#getColor(int, android.content.res.Resources.Theme)
     */
    @SuppressWarnings("deprecation")
    @SuppressLint("NewApi")
    public int getColor(int id) {
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP_MR1)
            return mResources.getColor(id, null);

        return mResources.getColor(id);
    }

    /**
     * Honor deprecation of
     * {@link android.content.res.Resources#getDrawable(int)} since API 22.
     *
     * @param id
     *            The desired resource identifier, as generated by the aapt
     *            tool. This integer encodes the package, type, and resource
     *            entry. The value 0 is an invalid identifier.
     * @return an object that can be used to draw this resource.
     */
    @SuppressWarnings("deprecation")
    @SuppressLint("NewApi")
    public Drawable getDrawable(int id) {
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT_WATCH)
            return mResources.getDrawable(id, null);

        return mResources.getDrawable(id);
    }

    /**
     * @param context
     *            A context object to access the
     *            {@link android.content.res.Resources} of the app.
     * @param id
     *            The desired resource identifier, as generated by the aapt
     *            tool. This integer encodes the package, type, and resource
     *            entry. The value 0 is an invalid identifier.
     * @return a single color value in the form 0xAARRGGBB.
     */
    public static int getColor(Context context, int id) {
        return new Resources(context).getColor(id);
    }

    /**
     * @param context
     *            A context object to access the
     *            {@link android.content.res.Resources} of the app.
     * @param id
     *            The desired resource identifier, as generated by the aapt
     *            tool. This integer encodes the package, type, and resource
     *            entry. The value 0 is an invalid identifier.
     * @return an object that can be used to draw this resource.
     */
    public static Drawable getDrawable(Context context, int id) {
        return new Resources(context).getDrawable(id);
    }
}
